### ISSUE TITLE
Not working, No error either

### ISSUE THREAD

**Issue by SurgicalCrow** [Dhruvin-Purohit/Brawl-Stars-Club-Tracker#2]
i am not either getting any error, it isnt even working, i set a console.log() inside the clubTracker.ready()  but it is not working

```
const { Tracker } = require('brawl-stars-club-tracker');
const blacklist = require("./database/models/blacklist")
const guild = client.guilds.cache.get("723146775262658571")
try {
for (const config of configs.clubs) {
const clubTag = config.tag

let clubTracker = new Tracker(clubTag, {
	token: 'BS TOken',
	useProxy: false,
	ratelimit: 2, //fetch 2 times every second (1 time every 0.5 seconds)
})

clubTracker.init();
clubTracker.once('ready', async (tracker) => {
  console.log(`Tracker is ready!`)
	tracker.on('clubMemberAdd', async (member, oldData, newData) => {
		const tag = member.tag

    const find = await blacklist.findOne({ tag: tag })
    if (find) {
      const channel = guild.channels.cache.find(x => x.name.includes("blacklist-warning"))
      if (channel) {
        channel.send(`A Player named ${member.name} with ${member.tag}, Who was blacklisted for ${find.reason} is in ${newData.name} club right now, kick him ASAP`)
      }
    }
    
	});
	tracker.on('error', (err) => {
		console.error(err);
	});
})

}
} catch (err) {
  console.log(err)
}
```

**Comment by Dhruvin-Purohit** [comment]
Completely forgot to add that for now, this does not work due to me not having time to fix the code and also I have my main exams coming up in a week so I will not be able to fix the code, you should use `@statscell/brawl` till then.

**Comment by SurgicalCrow** [comment]
> 
> 
> Completely forgot to add that for now, this does not work due to me not having time to fix the code and also I have my main exams coming up in a week so I will not be able to fix the code, you should use `@statscell/brawl` till then.

Can i track club logs there? i just want to inform in a discord channel whenever a blacklisted tag player joins the X Club, i dont see any option there like that in statscell/brawl

**Comment by SurgicalCrow** [comment]
and any time when you can fix that ? i can wait 2-3 weeks, np

**Comment by Dhruvin-Purohit** [comment]
> and any time when you can fix that? I can wait 2-3 weeks, np

I have my board exams coming up, I assume you might know that as you are from Bangladesh (your GitHub profile shows that.)

And well once those are over, I will start fixing the code, probably even rewriting them.

**Comment by Dhruvin-Purohit** [comment]
> > Completely forgot to add that for now, this does not work due to me not having time to fix the code and also I have my main exams coming up in a week so I will not be able to fix the code, you should use `@statscell/brawl` till then.
> 
> Can i track club logs there? i just want to inform in a discord channel whenever a blacklisted tag player joins the X Club, i dont see any option there like that in statscell/brawl

I found that in the code, https://github.com/TheLearneer/brawl-stars/blob/main/src/lib/Events.ts
